name: Atualizar Dados IPEA

on:
  schedule:
    - cron: '0 10 * * *'  # Executa todo dia 맙 04:00 UTC (01:00 em Bras칤lia)
  workflow_dispatch:     # Permite execu칞칚o manual no GitHub

permissions:
  contents: write  # Necess치rio para permitir push com GITHUB_TOKEN

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Clonar reposit칩rio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 游냀 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 游닍 Instalar depend칡ncias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 丘뙖잺 Rodar script ETL
        run: |
              python src/Efetivos/passo3.py &
              python src/Produ칞칚o/passo1.py &
              python src/Produ칞칚o/passo3.py &
              python src/area colhida/passo1.py &
              wait

      - name: 游대 Commit e push dos CSVs atualizados
        run: |
          git config user.name "jonasksa"
          git config user.email "jonaskasakewitch32@gmail.com"
          git add -A
          git commit -m "游늵 Atualiza칞칚o autom치tica dos dados do IPEA" || echo "Nenhuma altera칞칚o para commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
